sudo: required
dist: trusty

language: node_js

node_js:
  - "4"
  - "6"
  - "8"
  - "9"

os:
  - linux

matrix:
  fast_finish: true

before_install: './ci/before_install.sh'

before_script:
  - sudo mkdir /var/lib/clamav && sudo chmod 777 /var/lib/clamav
  - wget http://db.us.clamav.net/main.cvd -O /var/lib/clamav/main.cvd
  - wget http://db.us.clamav.net/daily.cvd -O /var/lib/clamav/daily.cvd
