language: node_js
matrix:
  fast_finish: true
  include:
    - node_js: "4.2"
    - node_js: "0.12"
    - node_js: "0.11"
    - node_js: "0.10"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libclamav-dev

before_script:
  - sudo mkdir /var/lib/clamav && sudo chmod 777 /var/lib/clamav
  - wget http://db.us.clamav.net/main.cvd -O /var/lib/clamav/main.cvd
  - wget http://db.us.clamav.net/daily.cvd -O /var/lib/clamav/daily.cvd
sudo: required
dist: trusty
