sudo: required
dist: trusty

language: node_js

node_js:
  - "4"
  - "6"
  - "8"
  - "9"

os:
  - linux
  - osx

matrix:
  fast_finish: true

before_install: './ci/before_install.sh'
before_script: './ci/before_script.sh'
